[package]
name = "Monologued"
version = "0.1.0"
authors = ["Elf M. Sternberg <elf.sternberg@gmail.com>"]

[dependencies]
mio = "0.6.10"
net2 = "0.2.31"
unicode-segmentation = "1.2.*"
bytes = "0.4.5"
log = "0.3"
env_logger = "0.4.*"
slab = "0.4"
